-keep class com.google.mlkit.** { *; }
-dontwarn com.google.mlkit.**
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn org.conscrypt.**
-dontwarn org.bouncycastle.**
-dontwarn org.openjsse.**
-keep class ai.onnxruntime.** { *; }
-dontwarn ai.onnxruntime.**
-keep class com.google.mlkit.vision.segmentation.** { *; }
